<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>local.jarios</groupId>
    <artifactId>jarios-parent</artifactId>
    <version>1.0.13</version>
    <relativePath>../jarios-parent/pom.xml</relativePath>
  </parent>
  <artifactId>import-from-opendata</artifactId>
  <version>7.3.2</version>
  <packaging>jar</packaging>
  <name>Importador de CODICE</name>
  <description>Cliente que parsea los ficheros atoms con los datos abiertos expuestos por la Plataforma de Contratación del Sector Público</description>
  <scm>
    <connection>scm:git:https://github.com/contratacionmalaga/import_from_opendata.git</connection>
    <developerConnection>scm:git:git@github.com:contratacionmalaga/import_from_opendata.git</developerConnection>
    <url>https://github.com/contratacionmalaga/import_from_opendata</url>
    <tag>HEAD</tag>
  </scm>
  <distributionManagement>
    <repository>
      <id>github-releases</id>
      <url>https://maven.pkg.github.com/contratacionmalaga/import_from_opendata</url>
    </repository>
    <snapshotRepository>
      <id>github-snapshots</id>
      <url>https://maven.pkg.github.com/contratacionmalaga/import_from_opendata</url>
    </snapshotRepository>
  </distributionManagement>
  <properties>
    <version.trimmed>${project.version}</version.trimmed>
    <final.name>${artifact.suffix}-${version.trimmed}-${profile.suffix}</final.name>
    <jaxb.core.version>2.3.0.1</jaxb.core.version>
    <jaxb.impl.version>2.3.1</jaxb.impl.version>
    <jaxb.api.version>2.4.0-b180830.0359</jaxb.api.version>
    <javax.activation.version>1.2.0</javax.activation.version>
    <atom.version>1.0</atom.version>
    <codice.version>2.8.0</codice.version>
    <codice.place.ext.version>1.5.0</codice.place.ext.version>
    <checkstyle.max.violations>0</checkstyle.max.violations>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-to-slf4j</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hibernate.orm</groupId>
      <artifactId>hibernate-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hibernate.orm</groupId>
      <artifactId>hibernate-hikaricp</artifactId>
    </dependency>
    <dependency>
      <groupId>com.zaxxer</groupId>
      <artifactId>HikariCP</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sun.xml.bind</groupId>
      <artifactId>jaxb-core</artifactId>
      <version>${jaxb.core.version}</version>
    </dependency>
    <dependency>
      <groupId>com.sun.xml.bind</groupId>
      <artifactId>jaxb-impl</artifactId>
      <version>${jaxb.impl.version}</version>
    </dependency>
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>${jaxb.api.version}</version>
    </dependency>
    <dependency>
      <groupId>javax.activation</groupId>
      <artifactId>javax.activation-api</artifactId>
      <version>${javax.activation.version}</version>
    </dependency>
    <dependency>
      <groupId>org.w3._2005.atom</groupId>
      <artifactId>atom</artifactId>
      <version>${atom.version}</version>
    </dependency>
    <dependency>
      <groupId>place.codice</groupId>
      <artifactId>codice</artifactId>
      <version>${codice.version}</version>
    </dependency>
    <dependency>
      <groupId>place.codice</groupId>
      <artifactId>codice-ext</artifactId>
      <version>${codice.place.ext.version}</version>
    </dependency>
    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>jakarta.mail</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-text</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-collections4</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
    </dependency>
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>local.jarios</groupId>
      <artifactId>encrypt-helper</artifactId>
    </dependency>
    <dependency>
      <groupId>local.jarios</groupId>
      <artifactId>version-helper</artifactId>
    </dependency>
    <dependency>
      <groupId>local.jarios</groupId>
      <artifactId>email-helper</artifactId>
    </dependency>
    <dependency>
      <groupId>local.jarios</groupId>
      <artifactId>properties-helper</artifactId>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <finalName>${final.name}</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <release>${maven.compiler.release}</release>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <useModulePath>false</useModulePath>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>${maven.minimum.version}</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
            </manifest>
            <manifestEntries>
              <App-Version>${project.version}</App-Version>
              <App-Name>${project.artifactId}</App-Name>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <release>${maven.compiler.release}</release>
          <show>private</show>
          <nohelp>true</nohelp>
          <doclint>none</doclint>
          <quiet>true</quiet>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <configuration>
          <tagNameFormat>v@{project.version}</tagNameFormat>
          <autoVersionSubmodules>true</autoVersionSubmodules>
          <scmCommentPrefix>[RELEASE]</scmCommentPrefix>
          <pushChanges>true</pushChanges>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <id>shade</id>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <finalName>${final.name}</finalName>
              <shadedArtifactAttached>false</shadedArtifactAttached>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/LICENSE*</exclude>
                    <exclude>META-INF/NOTICE*</exclude>
                  </excludes>
                </filter>
              </filters>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>${mainClass}</mainClass>
                  <manifestEntries>
                    <App-Version>${project.version}</App-Version>
                    <App-Name>${project.artifactId}</App-Name>
                  </manifestEntries>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                <transformer implementation="org.apache.maven.plugins.shade.resource.ApacheLicenseResourceTransformer" />
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <configuration>
          <includeFilterFile>src/main/resources/spotbugs-security-include.xml</includeFilterFile>
          <excludeFilterFile>src/main/resources/spotbugs-security-exclude.xml</excludeFilterFile>
          <plugins>
            <plugin>
              <groupId>com.h3xstream.findsecbugs</groupId>
              <artifactId>findsecbugs-plugin</artifactId>
              <version>${findsecbugs.plugin.version}</version>
            </plugin>
          </plugins>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>versions-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <configuration>
          <java>
            <googleJavaFormat>
              <version>${google.java.format.version}</version>
            </googleJavaFormat>
            <removeUnusedImports />
          </java>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>con-filtros-local</id>
      <properties>
        <mainClass>local.jarios.variants.malaga.OpenDataMalagaLocal</mainClass>
        <profile.suffix>local</profile.suffix>
        <artifact.suffix>opendata_con_filtros</artifact.suffix>
      </properties>
    </profile>
    <profile>
      <id>con-filtros-internet</id>
      <properties>
        <mainClass>local.jarios.variants.malaga.OpenDataMalagaInternet</mainClass>
        <profile.suffix>internet</profile.suffix>
        <artifact.suffix>opendata_con_filtros</artifact.suffix>
      </properties>
    </profile>
    <profile>
      <id>sin-filtros-local</id>
      <properties>
        <mainClass>local.jarios.variants.pliegos.OpenDataPliegosLocal</mainClass>
        <profile.suffix>local</profile.suffix>
        <artifact.suffix>opendata_sin_filtros</artifact.suffix>
      </properties>
    </profile>
    <profile>
      <id>sin-filtros-internet</id>
      <properties>
        <mainClass>local.jarios.variants.pliegos.OpenDataPliegosInternet</mainClass>
        <profile.suffix>internet</profile.suffix>
        <artifact.suffix>opendata_sin_filtros</artifact.suffix>
      </properties>
    </profile>
  </profiles>
</project>
