name: Java CI with Maven

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  release:
    types: [published]  # Opcional, si usas releases GitHub
  # O para activar por tags:

jobs:
  build:
    name: Build, Test, Site & Deploy SNAPSHOT
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build & test with Maven
        run: mvn clean verify

      - name: Generate Maven site
        run: mvn site

      - name: Upload Maven site
        uses: actions/upload-artifact@v4
        with:
          name: maven-site
          path: target/site

      - name: Run OWASP Dependency Check
        uses: dependency-check/owasp-dependency-check-action@v2
        with:
          project: 'import_from_gc'
          scanPath: '.'
          format: 'HTML'
          out: 'dependency-check-report'

      - name: Upload OWASP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: dependency-check-report

      - name: Deploy SNAPSHOT to GitHub Packages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ git_
