name: Setup project artifacts
description: Prepare project-specific local artifacts.

runs:
  using: composite
  steps:
    - name: Install local CODICE artifacts
      shell: bash
      run: |
        ./mvnw -B -ntp install:install-file -Dfile=lib/atom-1.0.jar -DgroupId=org.w3._2005.atom -DartifactId=atom -Dversion=1.0 -Dpackaging=jar
        ./mvnw -B -ntp install:install-file -Dfile=lib/codice-2.8.0.jar -DgroupId=place.codice -DartifactId=codice -Dversion=2.8.0 -Dpackaging=jar
        ./mvnw -B -ntp install:install-file -Dfile=lib/codice-ext-1.5.0.jar -DgroupId=place.codice -DartifactId=codice-ext -Dversion=1.5.0 -Dpackaging=jar
